### ISSUE TITLE
Increase Heading Font Size

### ISSUE THREAD

**Issue by vishaaal** [vishaaal/BookCase#1]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/69189572/194778331-feb7e80f-7a8a-4585-a7c5-3d8c211ecb3b.png">
Tasks:

- Increase the font
- Center text

**Comment by Wraytheon** [comment]
I can do this!

**Comment by Wraytheon** [comment]
It seems that the targeted element is already fairly large and centered, do you just want it to be bigger?

**Comment by vishaaal** [comment]
yes you may just center it in a way that it doesn't effect other elements @Wraytheon

**Comment by prabhat7k** [comment]
Can i work on this?

**Comment by sumitbaroniya** [comment]
Please assign me this issue

**Comment by Pranjal2870** [comment]
Please assign me this project @vishaaal
