### ISSUE TITLE
Responsiveness for small page

### ISSUE THREAD

**Issue by vishaaal** [vishaaal/BookCase#158]
Make the footer and header responsive for small pages.

**Comment by vishaaal** [comment]
- [ ] Footer
- [x] Header

**Comment by Ishikasaraf20** [comment]
hey @vishaaal can you assign this issue to me i can work on it

**Comment by vishaaal** [comment]
Sure @Ishikasaraf20

**Comment by vishaaal** [comment]
Please attach a screenshot in your pull request

**Comment by Saikatssd** [comment]
@vishaaal I have done it. Please assign me.

![4](https://user-images.githubusercontent.com/92164254/197377219-b3f6c42d-3c6b-4e95-96b3-4b50cceebf35.gif)

**Comment by Ishikasaraf20** [comment]
hey @vishaaal I've Raised the PR kindly review the changes and merge it to main branch

**Comment by Ishikasaraf20** [comment]
I've also attached the screenshot with it
