### ISSUE TITLE
Modify the toggle button into a cool toogle button icon

### ISSUE THREAD

**Issue by Saikatssd** [vishaaal/BookCase#162]
**Description of the feature you'd like to add.**
Modify the toggle button icon.

Screenshot Description

![ld](https://user-images.githubusercontent.com/92164254/197379304-defb8aec-2b11-49c3-b2ae-7ea7f611cb94.gif)

**Comment by Saikatssd** [comment]
Please Assign me.

**Comment by vishaaal** [comment]
Done
