### ISSUE TITLE
There are some issues in website i can solve that and also add a book so pls assign me this

### ISSUE THREAD

**Issue by kishanlalchoudhary** [vishaaal/BookCase#163]

**Comment by vishaaal** [comment]
State the issues

**Comment by kishanlalchoudhary** [comment]
![Screenshot (53)](https://user-images.githubusercontent.com/107745828/197585942-68901e83-ccef-4ac1-a27d-e7d2d2bee74b.png)

**Comment by kishanlalchoudhary** [comment]
check this

**Comment by kishanlalchoudhary** [comment]
so i want to add my book and also solve this issue

**Comment by kishanlalchoudhary** [comment]
can i solve it

**Comment by kishanlalchoudhary** [comment]
![Screenshot (55)](https://user-images.githubusercontent.com/107745828/197684141-92241ec1-d626-4185-a5e0-a37fbecd4b86.png)

**Comment by kishanlalchoudhary** [comment]
in some cards multiple time data is added

**Comment by kishanlalchoudhary** [comment]
![Uploading Screenshot (56).png…]()

**Comment by kishanlalchoudhary** [comment]
![Screenshot (56)](https://user-images.githubusercontent.com/107745828/197685226-eb09f38b-518b-4c4c-811e-b7a62efcdac5.png)

**Comment by kishanlalchoudhary** [comment]
this also
