### ISSUE TITLE
Updating the footer's copyright year required

### ISSUE THREAD

**Issue by tmsagarofficial** [vishaaal/BookCase#183]
**Describe the bug**
The issue is that in the footer section of the website, the copyright year is old and can be automated so that no need to change it every year.

**Expected behavior**
The year should be updated automatically as that of the current year

**Screenshots**
<img width="304" alt="image" src="https://user-images.githubusercontent.com/110724849/230784243-2d1d45db-742a-418c-804f-ca323b03ca0e.png">

**Additional context**

**Comment by tmsagarofficial** [comment]
@vishaaal Pls assign this to me so that I can start working on a fix for this issue. Would love to contribute to this project 🚀

**Comment by tmsagarofficial** [comment]
@vishaaal

**Comment by sasank-paria** [comment]
@vishaaal please assign this to me . I can fix that
