### ISSUE TITLE
Apply TypeWriter Effect on heading

### ISSUE THREAD

**Issue by vishaaal** [vishaaal/BookCase#2]
Follow this link to know more about Typewriter Effect:
https://css-tricks.com/snippets/css/typewriter-effect/
Text to be applied on:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/69189572/194778474-a4f5da49-1ae9-4e52-bf11-1b88b4d60519.png">

**Comment by NirvanaPhX** [comment]
I can work on this. Thanks!

**Comment by vishaaal** [comment]
Issue Solved
