### ISSUE TITLE
Issue Template Needed.

### ISSUE THREAD

**Issue by sohailg** [vishaaal/BookCase#30]

**Comment by sohailg** [comment]
I would like to work on it.

**Comment by vishaaal** [comment]
Can you please elaborate what you want to add to the Issue Template?

**Comment by vishaaal** [comment]
Okay Do it

**Comment by sohailg** [comment]
can you labelize  "hacktoberfest"

**Comment by sohailg** [comment]
Pull request done: https://github.com/vishaaal/BookCase/pull/31
