### ISSUE TITLE
Instagram heart feature 

### ISSUE THREAD

**Issue by vishaaal** [vishaaal/BookCase#33]
[**Is your feature request related to a problem? Please describe.**
A clear and concise desc]
https://codepen.io/bneupane/pen/KMKzZZ

**Describe the solution you'd like**
Implement the heart like feature and add it to each card. Go to the link mentioned above.

Each card should have this heart button beside contributors name

**Comment by jsvigneshkanna** [comment]
I would like to fix this issue, please assign me
