### ISSUE TITLE
Add feature to open and read the book.

### ISSUE THREAD

**Issue by prabhat7k** [vishaaal/BookCase#45]
Please assign this to me under hacktoberfest

**Comment by vishaaal** [comment]
How will they read the book? hehe

**Comment by rushiikudapane** [comment]
> How will they read the book? hehe

Links can be added to those book that are available free on google

**Comment by vishaaal** [comment]
Could be implemented when the site is made dynamic. Or else we need to add for every card. So leave.

**Comment by prabhat7k** [comment]
> Could be implemented when the site is made dynamic. Or else we need to add for every card. So leave.

I'll add downloadable links to the books card.. user will have option to download the book just by clicking the card.
