### ISSUE TITLE
Changing the Position of the text at home page 

### ISSUE THREAD

**Issue by VedVaghela** [vishaaal/BookCase#7]
The Text here is not visible and needs to be put at proper place

![image](https://user-images.githubusercontent.com/94840462/194800654-700cb27a-2564-4b60-a08b-0f17c32421ae.png)

**Comment by VedVaghela** [comment]
Can You please assign me this issue as a part of hacktober fest

**Comment by vishaaal** [comment]
Sure go ahead @VedVaghela
