### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by zugzwang03** [vishaaal/BookCase#8]
A website looks really complete with a footer. 
Can I work on this issue under hacktoberfest'22?

**Comment by vishaaal** [comment]
Sure go ahead. you might also add a book for the website

**Comment by zugzwang03** [comment]
Is the issue resolved already? @vishaaal

**Comment by vishaaal** [comment]
Can you do the *made with ♥️ by * footer with two social icons. I want to keep it simple @zugzwang03

**Comment by vishaaal** [comment]
Have re-opened the issue @zugzwang03

**Comment by zugzwang03** [comment]
Fine 🙂

**Comment by zugzwang03** [comment]
![footer](https://user-images.githubusercontent.com/95460021/195015377-bedeef5a-760e-4e05-8422-5e7f5a994a93.png)
how is this?

**Comment by vishaaal** [comment]
Great create a PR @zugzwang03

**Comment by vishaaal** [comment]
<img width="71" alt="image" src="https://user-images.githubusercontent.com/69189572/195030905-81594514-445f-4a17-9f4b-679c4f24a818.png">
Add this text on the right.. with the year 2022
