### ISSUE TITLE
Suggestion to change the favicon to something similar or exactly to that of the logo

### ISSUE THREAD

**Issue by tmsagarofficial** [vishaaal/BookCase#94]
**Is your feature request related to a problem? Please describe.**
I think it would be very easy and hassle-free to use if the website has both the favicon and the logo as same or something very similar.

**Describe the solution you'd like**
I would like to suggest to change either of the one not completely changing it but using the logo as the favicon as its very good looking already.

**Describe alternatives you've considered**
I would welcoe any other alternatives for the idea/issue i have quoted. Or may be i can help redesign a new logo with time given. I do undertand that this might not be a big issue for all but i feel this will enhance the presence and branding/identification of bookCase with uniqueness

**Additional context**
![image](https://user-images.githubusercontent.com/110724849/195098136-790e3510-35d4-472a-b777-0c946030559f.png)
![image](https://user-images.githubusercontent.com/110724849/195098825-21ac6a36-c917-439c-9835-cafd12b2985b.png)

I couldnt find any way to contact u like discord or so other than linkedin hence im creating this issue to discuss . pls dont mind
i am a haktoberfest22 participant 😅 

Pls do add the haktoberfest labels

**Comment by vishaaal** [comment]
you are supposed to raise an issue only and not directly contact me.
You can change any on of them as both favicon and logo, go ahead.

**Comment by tmsagarofficial** [comment]
@vishaaal Hi again, Thanks for assigning it to me. Will surely solve this _ASAP_ .

**Comment by tmsagarofficial** [comment]
I hav made the necessary changes and hav created a PR pls check and let me know.

**Comment by tmsagarofficial** [comment]
@vishaaal PLs check and let me know about the changes if necessary about the pr #104

**Comment by tmsagarofficial** [comment]
@vishaaal Thanks for letting me contribute. 🚀
