### ISSUE TITLE
Aesthetic Loader

### ISSUE THREAD

**Issue by vishaaal** [vishaaal/BookCase#96]
**Description of the feature you'd like to add.**
Add an aesthetic loader to the website

**Additional context**
Suggestions:
1. https://dribbble.com/shots/3208433-Simple-Book-Preloader
2. https://dribbble.com/shots/666482-Book-Loader
3. https://dribbble.com/shots/7425055-Book-Loader
4. https://dribbble.com/shots/4405331-Loader

**Comment by Kpallavi5** [comment]
I would like to work on this project can you please assign me?

**Comment by vishaaal** [comment]
> I would like to work on this project can you please assign me?

Let @sibayanmisra2002 do the work. Will update you for any further changes

**Comment by sibayanmisra2002** [comment]
> > I would like to work on this project can you please assign me?
> 
> Let @sibayanmisra2002 do the work. Will update you for any further changes

Done, please check PR.
